name: Database Submission
description: Contribute to A Few Games' video game database
title: "[Submission]: <game title, including subtitle(s)>"
labels: ["contribution"]
projects: ["geotrev/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution!

        ## What is this?

        Submitting with this form contributes to A Few Games' [video game database](https://afew.games), which exclusively tracks _box and seal variants_ of games.

        ## Before submitting

        Please review this checklist:

        * Proof read your submission for inaccuracies, such as typos
        * Links to official sources (e.g., press releases, publisher documentation) are encouraged
        * Links to eBay listings are encouraged
        * If the game has so little documentation and so few listings that it can't be easily referenced, say so in the notes

  - type: input
    id: platform
    attributes:
      label: Platform
      description: Specify which console the game released on.
      placeholder: E.g., SNES
    validations:
      required: true

  - type: input
    id: mpn
    attributes:
      label: MPN (Manufacturer's Part Number)
      description: A code used to identify a product at retail. Each publisher has a different format. If you're not sure about this, leave this blank. Typically found on the back of a game near the UPC.
      placeholder: E.g., ABC-DEFG-USA

  - type: input
    id: country
    attributes:
      label: Country
      description: The country of manufacture. Most games say 'Made in Japan,' 'Made in USA,' etc. If there's no country indicated, leave this blank. The MPN might specify the country, ending in 'USA,' 'CAN' (Canada), etc.
      placeholder: E.g., Japan

  - type: input
    id: part-code
    attributes:
      label: Part Code
      description: The unique identifier given to the game during manufacturing. Also called a 'product code.' Typically found on the spine or back of a game, near the UPC.
      placeholder: E.g., 12345B

  - type: textarea
    id: notes
    attributes:
      label: Additional Information
      description: Provide links to resources, additional context, or anything else useful to cross-verify this game.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting to the AFG database, you agree to follow our [Code of Conduct](https://github.com/geotrev/afew.games/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
