backend:
  name: "git-gateway"
  branch: "main"
  commit_message:
    create: "chore: create '{{slug}}'"
    update: "chore: update '{{slug}}'"
    delete: "chore: delete '{{slug}}'"
    uploadMedia: "chore: upload '{{slug}}'"
    deleteMedia: "chore: delete '{{slug}}'"
media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: "editorial_workflow"

collections:
  - name: "essays"
    label: "Essays"
    label_singular: "Essay"
    folder: "public/essays"
    preview_path: "public/essays/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    publish: true
    create: true
    fields:
      - label: "Title"
        name: "title"
        required: true
        widget: "string"
      - label: "Description"
        name: "description"
        required: true
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "databases"
    label: "Databases"
    editor:
      preview: false
    files:
      - label: "Graded Games"
        name: "graded_games"
        file: "public/games/collection.json"
        fields:
          - label: "Platforms"
            name: "platforms"
            widget: "list"
            label_singular: "Platform"
            allow_add: true
            add_to_top: true
            collapsed: true
            summary: "{{fields.platform}}"
            fields:
              - label: "Platform"
                name: "platform"
                widget: "string"
              - label: "Games"
                name: "games"
                widget: "list"
                label_singular: "Game"
                allow_add: true
                add_to_top: true
                collapsed: true
                summary: "{{fields.name}} - {{fields.grade}}"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Grade"
                    name: "grade"
                    widget: "string"
                  - label: "Variant"
                    required: false
                    name: "variant"
                    widget: "text"
                  - label: "Grader"
                    name: "grader"
                    widget: "select"
                    options: ["Wata", "VGA", "CGC", "P1G"]
      - label: "Video Game Variants"
        name: "video_game_variants"
        file: "public/variants/collection.json"
        fields:
          - label: "Platforms"
            name: "platforms"
            widget: "list"
            label_singular: "Platform"
            allow_add: true
            add_to_top: true
            collapsed: true
            summary: "{{fields.platform}}"
            fields:
              - label: "Platform"
                name: "platform"
                widget: "string"
              - label: "Games"
                name: "games"
                widget: "list"
                label_singular: "Game"
                allow_add: true
                add_to_top: true
                collapsed: true
                summary: "{{fields.name}}"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Variants"
                    name: "variants"
                    widget: "list"
                    label_singular: "Variant"
                    allow_add: true
                    add_to_top: true
                    collapsed: true
                    fields:
                      - label: "Part Code"
                        name: "part_code"
                        required: false
                        widget: "string"
                      - label: "Satellite Code"
                        name: "satellite_code"
                        required: false
                        widget: "string"
                      - label: "Manufactured"
                        name: "manufactured"
                        widget: "select"
                        required: false
                        options: ["USA", "Japan", "Mexico"]
                      - label: "MPN"
                        name: "mpn"
                        required: false
                        widget: "string"
                      - label: "Notes"
                        name: "notes"
                        required: false
                        widget: "text"
